<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dossier_model extends CI_Model
{

    public $table = 'dossier';
    public $id = 'idDossier';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idDossier', $q);
	$this->db->or_like('diplomeetatDossier', $q);
	$this->db->or_like('diplomesupDossier', $q);
	$this->db->or_like('lettredemandeDossier', $q);
	$this->db->or_like('annex1Dossier', $q);
	$this->db->or_like('annex2Dossier', $q);
	$this->db->or_like('annex3Dossier', $q);
	$this->db->or_like('nomEmpDossier', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idDossier', $q);
	$this->db->or_like('diplomeetatDossier', $q);
	$this->db->or_like('diplomesupDossier', $q);
	$this->db->or_like('lettredemandeDossier', $q);
	$this->db->or_like('annex1Dossier', $q);
	$this->db->or_like('annex2Dossier', $q);
	$this->db->or_like('annex3Dossier', $q);
	$this->db->or_like('nomEmpDossier', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dossier_model.php */
/* Location: ./application/models/Dossier_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-14 14:42:30 */
/* http://harviacode.com */